// File generated by FlutterFire CLI.
// Contains configuration options for Firebase.
// Replace the placeholder values with actual values from your Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can create these using the Firebase console.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can create these using the Firebase console.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can create these using the Firebase console.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can create these using the Firebase console.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these placeholder values with actual values from your Firebase project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzBN-G_60NIki6_1CFVlbKJdZ6g-21hhw',
    appId: '1:784836980732:android:3b3ce065dfdcaade590c79',
    messagingSenderId: 'REPLACE_WITH_ACTUAL_MESSAGING_SENDER_ID',
    projectId: 'donorly-bd',
    storageBucket: 'donorly-bd.firebasestorage.app',
  );

  // Replace these placeholder values with actual values from your Firebase project
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzBN-G_60NIki6_1CFVlbKJdZ6g-21hhw',
    appId: '1:784836980732:android:3b3ce065dfdcaade590c79',
    messagingSenderId: 'REPLACE_WITH_ACTUAL_MESSAGING_SENDER_ID',
    projectId: 'donorly-bd',
    storageBucket: 'donorly-bd.firebasestorage.app',
    iosClientId: 'REPLACE_WITH_ACTUAL_IOS_CLIENT_ID',
    iosBundleId: 'com.example.donorly',
  );
} 